I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 4287, in script
    menu:
  File "game/script.rpy", line 4289, in <module>
    "The mask." if not Peanut:
NameError: name 'Peanut' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 4287, in script
    menu:
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\ast.py", line 1632, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\exports\menuexports.py", line 100, in menu
    condition = renpy.python.py_eval(condition)
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\RENPY\renpy-8.3.4-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 4289, in <module>
    "The mask." if not Peanut:
NameError: name 'Peanut' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
